# This is a basic workflow to help you get started with Actions

name: 'Circle K prices fetch bot'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#   schedule:
#     - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bot"
  bot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4

      - name: Install dependencies
        run: npm install

      - name: Run the code
        run: node src/index.js
      
      - name: Commit and push changes
        run: |
          git config --global user.name "circlek bot"
          git config --global user.email "codermango@gamil.com"

          git add -A
          git commit --allow-empty -m "circle k price update"
          git push origin master
